# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(default='https://is5-ssl.mzstatic.com/image/thumb/Purple42/v4/d7/7e/e8/d77ee878-f5dd-f1d3-a93a-e19bba1f7183/source/256x256bb.jpg', max_length=255),
        ),
    ]
